# frozen_string_literal: true

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-thread_safety

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-rspec: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

# Disabled departments - not a Rails project, no Capybara/FactoryBot
Capybara:
  Enabled: false

FactoryBot:
  Enabled: false

RSpecRails:
  Enabled: false

# Layout
Layout/LineLength:
  Max: 100

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

# RSpec
RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/NestedGroups:
  Max: 4

RSpec/NoExpectationExample:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

# ThreadSafety
ThreadSafety/ClassAndModuleAttributes:
  Enabled: false

ThreadSafety/ClassInstanceVariable:
  Enabled: false

ThreadSafety/NewThread:
  Enabled: false
